name: build linux

on:
  push:
    branches:
      - master
  # push:
  #   paths:
  #     - ".github/workflows/build.yaml"
  #     - "pkgs/**"
  #     - "tasks/**"
  #     - "scripts/**"
  workflow_dispatch:
    inputs:
      name:
        description: "package name"
        default: ""
        required: false
        type: string
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        # task --list-all | sed -e 's/://g' -e 's/*/- name:/g'
        include:
          - name: aria2
          - name: atuin
          - name: autoconf
          - name: automake
          - name: bash
          - name: bat
          - name: bazelisk
          - name: binutils
          - name: bison
          - name: buildifier
          - name: bzip2
          - name: cacert
          - name: connect
          - name: coreutils
          - name: croc
          - name: curl
          - name: diffutils
          - name: dive
          - name: dool
          - name: ethtool
          - name: exiftool
          - name: eza
          - name: fd
          - name: file
          - name: findutils
          - name: flex
          - name: fzf
          - name: gawk
          - name: gdb
          - name: gdu
          - name: getopt
          - name: gettext
          - name: gh
          - name: git
          - name: git-absorb
          - name: git-extras
          - name: git-filter-repo
          - name: git-lfs
          - name: glibcLocales
          - name: gnugrep
          - name: gnumake
          - name: gnupatch
          - name: gnupg
          - name: gnused
          - name: gnutar
          - name: go-task
          - name: gost
          - name: gzip
          - name: indent
          - name: inetutils
          - name: iproute2
          - name: iptables
          - name: iputils
          - name: jq
          - name: krb5
          - name: less
          - name: libcap
          - name: libtool
          - name: lsb-release
          - name: lsof
          - name: m4
          - name: makeself
          - name: man
          - name: miniserve
          - name: ncdu_1
          - name: netcat
          - name: netron
          - name: nettools
          - name: ninja
          - name: nsight-systems
          - name: numactl
          - name: openssh_gssapi
          - name: openssl
          - name: patchelf
          - name: perl
          - name: pkg-config
          - name: procps
          - name: procs
          - name: protobuf_24
          - name: protobuf_25
          - name: protobuf_29
          - name: protobuf_3_8_0
          - name: protobuf_3_9_2
          - name: python311
          - name: rime-extra
          - name: ripgrep
          - name: rsync
          - name: ruff
          - name: scc
          - name: shfmt
          - name: snappy
          - name: starship
          - name: strace
          - name: tmux
          - name: tmux-extra
          - name: tree
          - name: tzdata
          - name: unzip
          - name: util-linux
          - name: vim
          - name: vim-extra
          - name: wget
          - name: xxd
          - name: xz
          - name: zellij
          - name: zip
          - name: zlib
          - name: zlib-ng
          - name: zsh
          - name: zsh-bundle
          - name: zstd
          - name: lua
          - name: cmake
          - name: cronie
          - name: p7zip
          - name: lefthook
          - name: yazi
          - name: uv

          # - name: nixfmt-rfc-style
          # - name: nixpkgs-fmt
          # - name: silver-searcher

    steps:
      - run: echo "skip_steps=true" >> $GITHUB_ENV
      - run: echo "skip_steps=false" >> $GITHUB_ENV
        if: ${{ (github.event_name == 'workflow_dispatch' && (inputs.name == matrix.name || inputs.name == '*')) || (github.event_name == 'push' && github.ref == 'refs/heads/master') }}

      - uses: actions/checkout@v4
        if: ${{ env.skip_steps != 'true' }}

      - run: ./docker/build.sh ${{ matrix.name }} linux-x86_64
        if: ${{ env.skip_steps != 'true' }}

      - uses: svenstaro/upload-release-action@v2
        if: ${{ env.skip_steps != 'true' }}
        with:
          file: ${{ matrix.name }}.linux-x86_64.tar.gz
          asset_name: ${{ matrix.name }}.linux-x86_64.tar.gz
          tag: "v1.0"
          overwrite: true

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30
