name: playgroud darwin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: Homebrew/actions/setup-homebrew@main
      - run: echo "/opt/homebrew/opt/binutils/bin" >> $GITHUB_PATH
      - run: brew install go-task binutils
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3"

      - uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - run: task -t tasks/common/Taskfile.yaml setup

      - uses: fawazahmed0/action-debug-vscode@main
        timeout-minutes: 45
